name: Keep Render Server Alive

# Schedule the workflow to run every 20 minutes
on:
  schedule:
    - cron: "*/20 * * * *"  # CRON syntax for 20-minute intervals

jobs:
  keep_server_alive:
    runs-on: ubuntu-latest

    steps:
      # Use curl to send a request to your server
      - name: Ping the Server
        run: |
          curl -X GET "https://asksitare.onrender.com/"
      
      # Send a POST to keep the Hugging Face Space warm
      - name: Keep Hugging Face Space Awake
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"text":"keepalive"}' \
            "https://aksherwal110-transformer.hf.space/embed"
          
